export type Period = "Baroque" | "Classical" | "Romantic" | "Modern";

export interface ClassicalPiece {
  id: string;
  title: string;
  composer: string;
  duration: number; // seconds
  type: string;
  period: Period;
  youtubeSearch: string;
}

// Duration coverage: ~45s to ~180 min
// ~160 curated pieces with typical performance durations
export const CLASSICAL_PIECES: ClassicalPiece[] = [
  // ── Under 2 minutes ──────────────────────────────────────────────────────────
  {
    id: "bach-minuet-g",
    title: "Minuet in G Major (BWV Anh. 114)",
    composer: "Johann Sebastian Bach",
    duration: 120,
    type: "Keyboard Piece",
    period: "Baroque",
    youtubeSearch: "Bach Minuet in G Major BWV Anh 114",
  },
  {
    id: "chopin-minute-waltz",
    title: "Waltz in D-flat Major 'Minute Waltz' Op. 64 No. 1",
    composer: "Frédéric Chopin",
    duration: 105,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Chopin Minute Waltz Op 64 No 1",
  },
  {
    id: "bach-prelude-c",
    title: "Prelude in C Major (Well-Tempered Clavier, BWV 846)",
    composer: "Johann Sebastian Bach",
    duration: 150,
    type: "Keyboard Piece",
    period: "Baroque",
    youtubeSearch: "Bach Prelude in C Major Well-Tempered Clavier BWV 846",
  },

  // ── 2–5 minutes ──────────────────────────────────────────────────────────────
  {
    id: "schumann-traumerei",
    title: "Träumerei (Kinderszenen, Op. 15 No. 7)",
    composer: "Robert Schumann",
    duration: 165,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Schumann Träumerei Kinderszenen Op 15",
  },
  {
    id: "saint-saens-swan",
    title: "The Swan (Le Cygne) from Carnival of the Animals",
    composer: "Camille Saint-Saëns",
    duration: 160,
    type: "Chamber Piece",
    period: "Romantic",
    youtubeSearch: "Saint-Saëns The Swan Le Cygne Carnival of Animals",
  },
  {
    id: "orff-o-fortuna",
    title: "O Fortuna (Carmina Burana)",
    composer: "Carl Orff",
    duration: 162,
    type: "Choral",
    period: "Modern",
    youtubeSearch: "Carl Orff O Fortuna Carmina Burana",
  },
  {
    id: "grieg-hall-mountain-king",
    title: "In the Hall of the Mountain King (Peer Gynt Suite No. 1)",
    composer: "Edvard Grieg",
    duration: 145,
    type: "Orchestral",
    period: "Romantic",
    youtubeSearch: "Grieg In the Hall of the Mountain King Peer Gynt",
  },
  {
    id: "beethoven-fur-elise",
    title: "Für Elise (Bagatelle in A Minor, WoO 59)",
    composer: "Ludwig van Beethoven",
    duration: 175,
    type: "Piano Piece",
    period: "Classical",
    youtubeSearch: "Beethoven Für Elise piano",
  },
  {
    id: "satie-gymnopedie-1",
    title: "Gymnopédie No. 1",
    composer: "Erik Satie",
    duration: 195,
    type: "Piano Piece",
    period: "Modern",
    youtubeSearch: "Erik Satie Gymnopédie No 1",
  },
  {
    id: "mozart-turkish-march",
    title: "Turkish March (Rondo alla Turca, K. 331)",
    composer: "Wolfgang Amadeus Mozart",
    duration: 180,
    type: "Piano Piece",
    period: "Classical",
    youtubeSearch: "Mozart Turkish March Rondo alla Turca K 331",
  },
  {
    id: "vivaldi-spring-1",
    title: "Spring – Allegro (The Four Seasons, 1st Movement)",
    composer: "Antonio Vivaldi",
    duration: 195,
    type: "Violin Concerto",
    period: "Baroque",
    youtubeSearch: "Vivaldi Spring Four Seasons first movement",
  },
  {
    id: "chopin-waltz-a-minor",
    title: "Waltz in A Minor, B. 150",
    composer: "Frédéric Chopin",
    duration: 135,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Chopin Waltz A Minor B150",
  },
  {
    id: "handel-hallelujah",
    title: "Hallelujah Chorus (Messiah, HWV 56)",
    composer: "George Frideric Handel",
    duration: 215,
    type: "Choral",
    period: "Baroque",
    youtubeSearch: "Handel Hallelujah Chorus Messiah",
  },
  {
    id: "schubert-ave-maria",
    title: "Ave Maria (Ellens Gesang III, D. 839)",
    composer: "Franz Schubert",
    duration: 255,
    type: "Vocal",
    period: "Romantic",
    youtubeSearch: "Schubert Ave Maria D 839",
  },
  {
    id: "chopin-fantasie-impromptu",
    title: "Fantaisie-Impromptu in C-sharp Minor, Op. 66",
    composer: "Frédéric Chopin",
    duration: 300,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Chopin Fantasie Impromptu Op 66",
  },
  {
    id: "chopin-nocturne-op9-2",
    title: "Nocturne in E-flat Major, Op. 9 No. 2",
    composer: "Frédéric Chopin",
    duration: 240,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Chopin Nocturne Op 9 No 2 E-flat major",
  },
  {
    id: "liszt-liebestraum-3",
    title: "Liebesträume No. 3 in A-flat Major",
    composer: "Franz Liszt",
    duration: 240,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Liszt Liebesträume No 3 piano",
  },

  // ── 5–10 minutes ─────────────────────────────────────────────────────────────
  {
    id: "satie-gnossienne-1",
    title: "Gnossienne No. 1",
    composer: "Erik Satie",
    duration: 255,
    type: "Piano Piece",
    period: "Modern",
    youtubeSearch: "Erik Satie Gnossienne No 1",
  },
  {
    id: "liszt-la-campanella",
    title: "La Campanella (Grandes Études de Paganini No. 3)",
    composer: "Franz Liszt",
    duration: 270,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Liszt La Campanella Grandes Études Paganini",
  },
  {
    id: "rachmaninoff-prelude-c-sharp",
    title: "Prelude in C-sharp Minor, Op. 3 No. 2",
    composer: "Sergei Rachmaninoff",
    duration: 210,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Rachmaninoff Prelude C sharp minor Op 3 No 2",
  },
  {
    id: "debussy-clair-de-lune",
    title: "Clair de Lune (Suite bergamasque, L. 75)",
    composer: "Claude Debussy",
    duration: 315,
    type: "Piano Piece",
    period: "Modern",
    youtubeSearch: "Debussy Clair de Lune piano",
  },
  {
    id: "bach-air-g-string",
    title: "Air on the G String (Orchestral Suite No. 3, BWV 1068)",
    composer: "Johann Sebastian Bach",
    duration: 210,
    type: "Orchestral",
    period: "Baroque",
    youtubeSearch: "Bach Air on the G String Orchestral Suite 3",
  },
  {
    id: "pachelbel-canon",
    title: "Canon in D Major",
    composer: "Johann Pachelbel",
    duration: 300,
    type: "Chamber Music",
    period: "Baroque",
    youtubeSearch: "Pachelbel Canon in D Major",
  },
  {
    id: "chopin-nocturne-op55-1",
    title: "Nocturne in F Minor, Op. 55 No. 1",
    composer: "Frédéric Chopin",
    duration: 315,
    type: "Piano Piece",
    period: "Romantic",
    youtubeSearch: "Chopin Nocturne F minor Op 55 No 1",
  },
  {
    id: "beethoven-moonlight-1st",
    title: "Moonlight Sonata – 1st Movement (Op. 27 No. 2)",
    composer: "Ludwig van Beethoven",
    duration: 330,
    type: "Piano Sonata Movement",
    period: "Classical",
    youtubeSearch: "Beethoven Moonlight Sonata first movement",
  },
  {
    id: "beethoven-moonlight-3rd",
    title: "Moonlight Sonata – 3rd Movement, Presto agitato",
    composer: "Ludwig van Beethoven",
    duration: 390,
    type: "Piano Sonata Movement",
    period: "Classical",
    youtubeSearch: "Beethoven Moonlight Sonata third movement Presto agitato",
  },
  {
    id: "wagner-ride-valkyries",
    title: "Ride of the Valkyries (Die Walküre, Act III)",
    composer: "Richard Wagner",
    duration: 480,
    type: "Orchestral",
    period: "Romantic",
    youtubeSearch: "Wagner Ride of the Valkyries",
  },
  {
    id: "holst-mars",
    title: "Mars, the Bringer of War (The Planets, Op. 32)",
    composer: "Gustav Holst",
    duration: 450,
    type: "Orchestral Suite Movement",
    period: "Modern",
    youtubeSearch: "Holst Mars Bringer of War The Planets",
  },
  {
    id: "debussy-prelude-afternoon",
    title: "Prélude à l'après-midi d'un faune",
    composer: "Claude Debussy",
    duration: 660,
    type: "Orchestral",
    period: "Modern",
    youtubeSearch: "Debussy Prelude Afternoon Faun L'après-midi",
  },
  {
    id: "holst-jupiter",
    title: "Jupiter, the Bringer of Jollity (The Planets, Op. 32)",
    composer: "Gustav Holst",
    duration: 450,
    type: "Orchestral Suite Movement",
    period: "Modern",
    youtubeSearch: "Holst Jupiter Bringer of Jollity The Planets",
  },
  {
    id: "bach-toccata-fugue",
    title: "Toccata and Fugue in D Minor, BWV 565",
    composer: "Johann Sebastian Bach",
    duration: 540,
    type: "Organ Piece",
    period: "Baroque",
    youtubeSearch: "Bach Toccata and Fugue D Minor BWV 565 organ",
  },
  {
    id: "vivaldi-spring-complete",
    title: "Spring (The Four Seasons) – Complete Concerto",
    composer: "Antonio Vivaldi",
    duration: 630,
    type: "Violin Concerto",
    period: "Baroque",
    youtubeSearch: "Vivaldi Spring Four Seasons complete concerto",
  },
  {
    id: "vivaldi-winter-complete",
    title: "Winter (The Four Seasons) – Complete Concerto",
    composer: "Antonio Vivaldi",
    duration: 600,
    type: "Violin Concerto",
    period: "Baroque",
    youtubeSearch: "Vivaldi Winter Four Seasons complete concerto",
  },
  {
    id: "vivaldi-summer-complete",
    title: "Summer (The Four Seasons) – Complete Concerto",
    composer: "Antonio Vivaldi",
    duration: 630,
    type: "Violin Concerto",
    period: "Baroque",
    youtubeSearch: "Vivaldi Summer Four Seasons complete concerto",
  },
  {
    id: "vivaldi-autumn-complete",
    title: "Autumn (The Four Seasons) – Complete Concerto",
    composer: "Antonio Vivaldi",
    duration: 630,
    type: "Violin Concerto",
    period: "Baroque",
    youtubeSearch: "Vivaldi Autumn Four Seasons complete concerto",
  },

  // ── 10–20 minutes ────────────────────────────────────────────────────────────
  {
    id: "bach-brandeburg-3",
    title: "Brandenburg Concerto No. 3 in G Major, BWV 1048",
    composer: "Johann Sebastian Bach",
    duration: 600,
    type: "Chamber Concerto",
    period: "Baroque",
    youtubeSearch: "Bach Brandenburg Concerto No 3 BWV 1048",
  },
  {
    id: "beethoven-moonlight-complete",
    title: "Moonlight Sonata – Complete (Op. 27 No. 2)",
    composer: "Ludwig van Beethoven",
    duration: 870,
    type: "Piano Sonata",
    period: "Classical",
    youtubeSearch: "Beethoven Moonlight Sonata complete Op 27 No 2",
  },
  {
    id: "ravel-bolero",
    title: "Boléro",
    composer: "Maurice Ravel",
    duration: 900,
    type: "Orchestral",
    period: "Modern",
    youtubeSearch: "Ravel Boléro orchestra",
  },
  {
    id: "tchaikovsky-1812",
    title: "1812 Overture, Op. 49",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 960,
    type: "Orchestral",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky 1812 Overture orchestra",
  },
  {
    id: "beethoven-pathetique-complete",
    title: "Piano Sonata 'Pathétique', Op. 13 – Complete",
    composer: "Ludwig van Beethoven",
    duration: 1080,
    type: "Piano Sonata",
    period: "Classical",
    youtubeSearch: "Beethoven Pathétique Sonata Op 13 complete",
  },
  {
    id: "grieg-peer-gynt-1",
    title: "Peer Gynt Suite No. 1, Op. 46",
    composer: "Edvard Grieg",
    duration: 1320,
    type: "Orchestral Suite",
    period: "Romantic",
    youtubeSearch: "Grieg Peer Gynt Suite No 1 Op 46",
  },
  {
    id: "bach-violin-partita-2-chaconne",
    title: "Chaconne from Partita No. 2 in D Minor, BWV 1004",
    composer: "Johann Sebastian Bach",
    duration: 840,
    type: "Solo Violin",
    period: "Baroque",
    youtubeSearch: "Bach Chaconne Partita No 2 D minor BWV 1004 violin",
  },
  {
    id: "mozart-piano-sonata-11",
    title: "Piano Sonata No. 11 in A Major, K. 331 – Complete",
    composer: "Wolfgang Amadeus Mozart",
    duration: 1200,
    type: "Piano Sonata",
    period: "Classical",
    youtubeSearch: "Mozart Piano Sonata K 331 A major complete",
  },

  // ── 18–30 minutes ────────────────────────────────────────────────────────────
  {
    id: "mozart-eine-kleine",
    title: "Eine kleine Nachtmusik, K. 525",
    composer: "Wolfgang Amadeus Mozart",
    duration: 1140,
    type: "Chamber Music",
    period: "Classical",
    youtubeSearch: "Mozart Eine kleine Nachtmusik K 525",
  },
  {
    id: "schubert-symphony-8",
    title: "Symphony No. 8 'Unfinished' in B Minor, D. 759",
    composer: "Franz Schubert",
    duration: 1500,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Schubert Symphony No 8 Unfinished D 759",
  },
  {
    id: "haydn-surprise-symphony",
    title: "Symphony No. 94 'Surprise' in G Major, Hob.I:94",
    composer: "Joseph Haydn",
    duration: 1380,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Haydn Symphony No 94 Surprise",
  },
  {
    id: "rachmaninoff-vocalise",
    title: "Vocalise, Op. 34 No. 14",
    composer: "Sergei Rachmaninoff",
    duration: 360,
    type: "Vocal/Orchestral",
    period: "Romantic",
    youtubeSearch: "Rachmaninoff Vocalise Op 34 No 14",
  },
  {
    id: "mendelssohn-violin-concerto",
    title: "Violin Concerto in E Minor, Op. 64",
    composer: "Felix Mendelssohn",
    duration: 1740,
    type: "Violin Concerto",
    period: "Romantic",
    youtubeSearch: "Mendelssohn Violin Concerto E minor Op 64",
  },
  {
    id: "mendelssohn-italian-symphony",
    title: "Symphony No. 4 'Italian' in A Major, Op. 90",
    composer: "Felix Mendelssohn",
    duration: 1620,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Mendelssohn Symphony No 4 Italian Op 90",
  },
  {
    id: "rachmaninoff-rhapsody-paganini",
    title: "Rhapsody on a Theme of Paganini, Op. 43",
    composer: "Sergei Rachmaninoff",
    duration: 1380,
    type: "Piano Concerto",
    period: "Romantic",
    youtubeSearch: "Rachmaninoff Rhapsody Paganini Op 43 piano",
  },
  {
    id: "mozart-symphony-40",
    title: "Symphony No. 40 in G Minor, K. 550",
    composer: "Wolfgang Amadeus Mozart",
    duration: 1800,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Mozart Symphony No 40 G minor K 550",
  },
  {
    id: "dvorak-9th-new-world-2nd",
    title: "Symphony No. 9 'New World' – Largo (2nd Movement)",
    composer: "Antonín Dvořák",
    duration: 670,
    type: "Symphony Movement",
    period: "Romantic",
    youtubeSearch: "Dvořák New World Symphony Largo 2nd movement",
  },

  // ── 30–45 minutes ────────────────────────────────────────────────────────────
  {
    id: "beethoven-symphony-5",
    title: "Symphony No. 5 in C Minor, Op. 67",
    composer: "Ludwig van Beethoven",
    duration: 2040,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Beethoven Symphony No 5 C minor Op 67",
  },
  {
    id: "beethoven-symphony-7",
    title: "Symphony No. 7 in A Major, Op. 92",
    composer: "Ludwig van Beethoven",
    duration: 2280,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Beethoven Symphony No 7 A major Op 92",
  },
  {
    id: "haydn-london-symphony",
    title: "Symphony No. 104 'London' in D Major, Hob.I:104",
    composer: "Joseph Haydn",
    duration: 1800,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Haydn Symphony No 104 London",
  },
  {
    id: "mozart-symphony-41",
    title: "Symphony No. 41 'Jupiter' in C Major, K. 551",
    composer: "Wolfgang Amadeus Mozart",
    duration: 1980,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Mozart Symphony No 41 Jupiter K 551",
  },
  {
    id: "tchaikovsky-piano-concerto-1",
    title: "Piano Concerto No. 1 in B-flat Minor, Op. 23",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 1980,
    type: "Piano Concerto",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky Piano Concerto No 1 B-flat minor Op 23",
  },
  {
    id: "rachmaninoff-piano-concerto-2",
    title: "Piano Concerto No. 2 in C Minor, Op. 18",
    composer: "Sergei Rachmaninoff",
    duration: 2100,
    type: "Piano Concerto",
    period: "Romantic",
    youtubeSearch: "Rachmaninoff Piano Concerto No 2 C minor Op 18",
  },
  {
    id: "tchaikovsky-violin-concerto",
    title: "Violin Concerto in D Major, Op. 35",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 2100,
    type: "Violin Concerto",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky Violin Concerto D major Op 35",
  },
  {
    id: "tchaikovsky-nutcracker-suite",
    title: "The Nutcracker Suite, Op. 71a",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 1350,
    type: "Orchestral Suite",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky Nutcracker Suite Op 71a",
  },
  {
    id: "mussorgsky-pictures-exhibition",
    title: "Pictures at an Exhibition (orch. Ravel)",
    composer: "Modest Mussorgsky / Maurice Ravel",
    duration: 1800,
    type: "Orchestral",
    period: "Romantic",
    youtubeSearch: "Mussorgsky Pictures at an Exhibition Ravel orchestration",
  },
  {
    id: "stravinsky-rite-of-spring",
    title: "The Rite of Spring",
    composer: "Igor Stravinsky",
    duration: 2100,
    type: "Ballet",
    period: "Modern",
    youtubeSearch: "Stravinsky Rite of Spring ballet",
  },
  {
    id: "vivaldi-four-seasons-complete",
    title: "The Four Seasons – Complete",
    composer: "Antonio Vivaldi",
    duration: 2520,
    type: "Violin Concertos",
    period: "Baroque",
    youtubeSearch: "Vivaldi Four Seasons complete all four concertos",
  },
  {
    id: "beethoven-violin-concerto",
    title: "Violin Concerto in D Major, Op. 61",
    composer: "Ludwig van Beethoven",
    duration: 2460,
    type: "Violin Concerto",
    period: "Classical",
    youtubeSearch: "Beethoven Violin Concerto D major Op 61",
  },
  {
    id: "dvorak-cello-concerto",
    title: "Cello Concerto in B Minor, Op. 104",
    composer: "Antonín Dvořák",
    duration: 2400,
    type: "Cello Concerto",
    period: "Romantic",
    youtubeSearch: "Dvořák Cello Concerto B minor Op 104",
  },
  {
    id: "rimsky-scheherazade",
    title: "Scheherazade, Op. 35",
    composer: "Nikolai Rimsky-Korsakov",
    duration: 2520,
    type: "Orchestral Suite",
    period: "Romantic",
    youtubeSearch: "Rimsky-Korsakov Scheherazade Op 35",
  },
  {
    id: "tchaikovsky-swan-lake-suite",
    title: "Swan Lake Suite, Op. 20a",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 1500,
    type: "Orchestral Suite",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky Swan Lake Suite Op 20a",
  },

  // ── 45–60 minutes ────────────────────────────────────────────────────────────
  {
    id: "beethoven-symphony-6",
    title: "Symphony No. 6 'Pastoral' in F Major, Op. 68",
    composer: "Ludwig van Beethoven",
    duration: 2340,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Beethoven Symphony No 6 Pastoral F major Op 68",
  },
  {
    id: "brahms-symphony-1",
    title: "Symphony No. 1 in C Minor, Op. 68",
    composer: "Johannes Brahms",
    duration: 2700,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Brahms Symphony No 1 C minor Op 68",
  },
  {
    id: "brahms-symphony-2",
    title: "Symphony No. 2 in D Major, Op. 73",
    composer: "Johannes Brahms",
    duration: 2520,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Brahms Symphony No 2 D major Op 73",
  },
  {
    id: "brahms-symphony-4",
    title: "Symphony No. 4 in E Minor, Op. 98",
    composer: "Johannes Brahms",
    duration: 2400,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Brahms Symphony No 4 E minor Op 98",
  },
  {
    id: "brahms-violin-concerto",
    title: "Violin Concerto in D Major, Op. 77",
    composer: "Johannes Brahms",
    duration: 2400,
    type: "Violin Concerto",
    period: "Romantic",
    youtubeSearch: "Brahms Violin Concerto D major Op 77",
  },
  {
    id: "rachmaninoff-piano-concerto-3",
    title: "Piano Concerto No. 3 in D Minor, Op. 30",
    composer: "Sergei Rachmaninoff",
    duration: 2400,
    type: "Piano Concerto",
    period: "Romantic",
    youtubeSearch: "Rachmaninoff Piano Concerto No 3 D minor Op 30",
  },
  {
    id: "tchaikovsky-symphony-4",
    title: "Symphony No. 4 in F Minor, Op. 36",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 2520,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky Symphony No 4 F minor Op 36",
  },
  {
    id: "tchaikovsky-symphony-5",
    title: "Symphony No. 5 in E Minor, Op. 64",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 2760,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky Symphony No 5 E minor Op 64",
  },
  {
    id: "tchaikovsky-symphony-6",
    title: "Symphony No. 6 'Pathétique' in B Minor, Op. 74",
    composer: "Pyotr Ilyich Tchaikovsky",
    duration: 2760,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Tchaikovsky Symphony No 6 Pathétique B minor Op 74",
  },
  {
    id: "dvorak-symphony-9",
    title: "Symphony No. 9 'From the New World' in E Minor, Op. 95",
    composer: "Antonín Dvořák",
    duration: 2520,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Dvořák Symphony No 9 New World E minor Op 95",
  },
  {
    id: "elgar-cello-concerto",
    title: "Cello Concerto in E Minor, Op. 85",
    composer: "Edward Elgar",
    duration: 1800,
    type: "Cello Concerto",
    period: "Romantic",
    youtubeSearch: "Elgar Cello Concerto E minor Op 85",
  },
  {
    id: "sibelius-symphony-2",
    title: "Symphony No. 2 in D Major, Op. 43",
    composer: "Jean Sibelius",
    duration: 2640,
    type: "Symphony",
    period: "Modern",
    youtubeSearch: "Sibelius Symphony No 2 D major Op 43",
  },
  {
    id: "debussy-la-mer",
    title: "La Mer (The Sea), L. 109",
    composer: "Claude Debussy",
    duration: 1440,
    type: "Orchestral",
    period: "Modern",
    youtubeSearch: "Debussy La Mer orchestral",
  },
  {
    id: "stravinsky-firebird",
    title: "The Firebird – Complete Ballet",
    composer: "Igor Stravinsky",
    duration: 2700,
    type: "Ballet",
    period: "Modern",
    youtubeSearch: "Stravinsky Firebird complete ballet",
  },
  {
    id: "holst-planets-complete",
    title: "The Planets, Op. 32 – Complete Suite",
    composer: "Gustav Holst",
    duration: 2880,
    type: "Orchestral Suite",
    period: "Modern",
    youtubeSearch: "Holst The Planets complete suite Op 32",
  },
  {
    id: "bruckner-symphony-7",
    title: "Symphony No. 7 in E Major",
    composer: "Anton Bruckner",
    duration: 4020,
    type: "Symphony",
    period: "Romantic",
    youtubeSearch: "Bruckner Symphony No 7 E major",
  },

  // ── 50–80 minutes ────────────────────────────────────────────────────────────
  {
    id: "beethoven-symphony-3",
    title: "Symphony No. 3 'Eroica' in E-flat Major, Op. 55",
    composer: "Ludwig van Beethoven",
    duration: 2940,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Beethoven Symphony No 3 Eroica E-flat Op 55",
  },
  {
    id: "mozart-requiem",
    title: "Requiem in D Minor, K. 626",
    composer: "Wolfgang Amadeus Mozart",
    duration: 3000,
    type: "Choral",
    period: "Classical",
    youtubeSearch: "Mozart Requiem D minor K 626",
  },
  {
    id: "bach-goldberg-variations",
    title: "Goldberg Variations, BWV 988",
    composer: "Johann Sebastian Bach",
    duration: 4500,
    type: "Keyboard Variations",
    period: "Baroque",
    youtubeSearch: "Bach Goldberg Variations BWV 988",
  },
  {
    id: "verdi-requiem",
    title: "Requiem",
    composer: "Giuseppe Verdi",
    duration: 5400,
    type: "Choral",
    period: "Romantic",
    youtubeSearch: "Verdi Requiem choral",
  },
  {
    id: "mahler-symphony-5",
    title: "Symphony No. 5 in C-sharp Minor",
    composer: "Gustav Mahler",
    duration: 4200,
    type: "Symphony",
    period: "Modern",
    youtubeSearch: "Mahler Symphony No 5 C sharp minor",
  },
  {
    id: "mahler-symphony-9",
    title: "Symphony No. 9 in D Major",
    composer: "Gustav Mahler",
    duration: 4800,
    type: "Symphony",
    period: "Modern",
    youtubeSearch: "Mahler Symphony No 9 D major",
  },
  {
    id: "brahms-piano-concerto-2",
    title: "Piano Concerto No. 2 in B-flat Major, Op. 83",
    composer: "Johannes Brahms",
    duration: 2880,
    type: "Piano Concerto",
    period: "Romantic",
    youtubeSearch: "Brahms Piano Concerto No 2 B flat major Op 83",
  },

  // ── 80–120 minutes ────────────────────────────────────────────────────────────
  {
    id: "beethoven-symphony-9",
    title: "Symphony No. 9 'Choral' in D Minor, Op. 125",
    composer: "Ludwig van Beethoven",
    duration: 4020,
    type: "Symphony",
    period: "Classical",
    youtubeSearch: "Beethoven Symphony No 9 Choral D minor Op 125",
  },
  {
    id: "mahler-symphony-6",
    title: "Symphony No. 6 'Tragic' in A Minor",
    composer: "Gustav Mahler",
    duration: 4740,
    type: "Symphony",
    period: "Modern",
    youtubeSearch: "Mahler Symphony No 6 Tragic A minor",
  },
  {
    id: "mahler-symphony-3",
    title: "Symphony No. 3 in D Minor",
    composer: "Gustav Mahler",
    duration: 6000,
    type: "Symphony",
    period: "Modern",
    youtubeSearch: "Mahler Symphony No 3 D minor",
  },
  {
    id: "mahler-symphony-2",
    title: "Symphony No. 2 'Resurrection' in C Minor",
    composer: "Gustav Mahler",
    duration: 5100,
    type: "Symphony",
    period: "Modern",
    youtubeSearch: "Mahler Symphony No 2 Resurrection C minor",
  },
  {
    id: "bach-well-tempered-clavier-1",
    title: "The Well-Tempered Clavier, Book I, BWV 846–869",
    composer: "Johann Sebastian Bach",
    duration: 6900,
    type: "Keyboard Collection",
    period: "Baroque",
    youtubeSearch: "Bach Well-Tempered Clavier Book I complete BWV 846",
  },
  {
    id: "handel-messiah",
    title: "Messiah, HWV 56 – Complete Oratorio",
    composer: "George Frideric Handel",
    duration: 8400,
    type: "Oratorio",
    period: "Baroque",
    youtubeSearch: "Handel Messiah complete oratorio HWV 56",
  },
  {
    id: "bach-st-matthew-passion",
    title: "St. Matthew Passion, BWV 244",
    composer: "Johann Sebastian Bach",
    duration: 9600,
    type: "Choral / Passion",
    period: "Baroque",
    youtubeSearch: "Bach St Matthew Passion BWV 244",
  },
];

/**
 * Find the closest classical pieces to a given duration.
 * Returns up to `count` pieces sorted by absolute difference from targetSeconds.
 */
export function findClosestPieces(
  targetSeconds: number,
  count: number = 3
): (ClassicalPiece & { diffSeconds: number; diffPercent: number })[] {
  return CLASSICAL_PIECES.map((piece) => ({
    ...piece,
    diffSeconds: Math.abs(piece.duration - targetSeconds),
    diffPercent:
      Math.round(
        (Math.abs(piece.duration - targetSeconds) / targetSeconds) * 1000
      ) / 10,
  }))
    .sort((a, b) => a.diffSeconds - b.diffSeconds)
    .slice(0, count);
}

export function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  if (h > 0) {
    return `${h}h ${m}m`;
  }
  if (m > 0 && s > 0) {
    return `${m}m ${s}s`;
  }
  if (m > 0) {
    return `${m} min`;
  }
  return `${s}s`;
}
